export const ROUTES = {
  HOME: "/home",
  EXPLORE: "/explore",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  EVENT_DETAILS: "/event/:id",
  RESET_PASSWORD: "/reset-password",
  DELETE_ACCOUNT: "/delete-account",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_OF_SERVICES: "/terms-of-services",
  PAYMENTS: "/payments",
  NOTIFICATIONS_SETTINGS: "/notifications-settings",
};
