export const MODALS = {
    EVENT_CONFIRMATION: "EVENT_CONFIRMATION",
    PAYMENT_WITHDRAW:"PAYMENT_WITHDRAW",
    EVENT_FLAG: "EVENT_FLAG",
    TAGS: "TAGS",
    TAGS_EXPLORER: "TAGS_EXPLORER",
    SORT_FILTER: "SORT_FILTER",
    ADD_KEYWORD: "ADD_KEYWORD",
};
